title: Archisa's Cool Blog B)
author: goldfishsmores
email: archisa28@gmail.com
description: > # this means to ignore newlines until "baseurl:"
Hey! this is my blog :) Here's a little 'brag sheet' -
  -Leader and 3 year competitor of Girls Go Cyberstart
  -Gold Medalist in Hospitality 101 FCCLA 2019 competition
  -Volunteer at Sunrise Assissted Living Facility

# social links
twitter_username: Archisa2 # DO NOT include the @ character, or else the build will fail!
github_username:  goldfishsmores # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
